pipeline {
    agent any

    parameters {
        string(name: 'APP_VERSION', defaultValue: '1.0.0', description: 'New version to set in all chart.yaml files')
    }

    environment {
        // Pass new version from Jenkins parameter or calculate dynamicallY
        NEW_VERSION = "${params.VERSION}"
        NEW_APP_VERSION = "${params.APP_VERSION}"
        
    }

    stages {

        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/main"]],
                    userRemoteConfigs: [[
                        url: 'https://github.com/vishaal99/azure.git',
                        credentialsId: 'github_pat'
                    ]]
                ])
            }
        }

        stage('Update Helm chart versions') {
            steps {
                script {
                    echo "Updating all chart.yaml files to version: ${NEW_VERSION}"
                    // Find every chart.yaml file under the repo and update version + appVersion
                    sh """
                    for file in \$(find . -name "Chart.yaml"); do
                        echo "Updating \$file"
                         # Update version
                        sed -i "s/^version: .*/version: \${NEW_VERSION}/" \$file
                        # Update appVersion
                        sed -i "s/^appVersion: .*/appVersion: \\"\${NEW_VERSION}\\"/" \$file
                    done
                    """
                }
            }
        }

        stage('Commit & Push CHANGES') {
            steps {
               withCredentials([string(credentialsId: 'github_pat', variable: 'GITHUB_PAT')]){

                    sh """
                    git config user.email "vishaalaadhityas@gmail.com"
                    git config user.name "vishaal99"
                    git remote set-url origin https://vishaal99:\${GITHUB_PAT}@github.com/vishaal99/azure.git
                    git add .
                    git commit -m "CD: Update chart version to \${NEW_VERSION}" || echo "No changes to commit"
                    # Push only if commit exists
                    git push origin HEAD:refs/heads/main || true
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished."
        }
    }
}
