pipeline {
    agent any

    parameters {
        string(name: 'VERSION_TO_UPDATE', description: 'New version to set in all chart.yaml files')
        string(name: 'APP_VERSION_UPDATE', description: 'New appVersion to set in all chart.yaml files')
    }

    environment {
        // Pass new version from Jenkins parameter or calculate dynamicallY
        NEW_VERSION = "${params.VERSION_TO_UPDATE}"
        NEW_APP_VERSION = "${params.APP_VERSION_UPDATE}"
        
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Checkout"
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/main"]],
                    userRemoteConfigs: [[
                        url: 'https://github.com/vishaal99/azure.git',
                        credentialsId: 'github-creds'
                    ]]
                ])
            }
        }

        stage('Update Helm chart versions') {
            steps {
                echo "updating"
                script {
                    
                    // Find every chart.yaml file under the repo and update version + appVersion
                    sh """
                    for file in \$(find . -name "Chart.yaml"); do
                        echo "Updating \$file"
                        # Update version
                        echo "Updating all chart.yaml files to version: \${NEW_VERSION}"
                        sed -i "s/^version: .*/version: \${NEW_VERSION}/" \$file
                        # Update appVersion
                        echo "Updating all chart.yaml files to appversion: \${NEW_APP_VERSION}"
                        sed -i "s/^appVersion: .*/appVersion: \"\${NEW_APP_VERSION}\"/" \$file

                    done
                    """
                }
            }
        }

        stage('Commit & Push CHANGES') {
            steps {
                echo "pushing"
                withCredentials([string(credentialsId: 'github_pat', variable: 'GITHUB_PAT')]){

                    sh """
                    git config user.email "vishaalaadhityas@gmail.com"
                    git config user.name "vishaal99"
                    git remote set-url origin https://vishaal99:\${GITHUB_PAT}@github.com/vishaal99/azure.git
                    git add .
                    git commit -m "CD: Updated chart version to \${NEW_VERSION} and appVersion to \${NEW_APP_VERSION}" || echo "No changes to commit"
                    # Push only if commit exists
                    git push origin HEAD:refs/heads/main || true
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished."
        }
    }
}
